name: "Grafana"
version: "dev"
slug: "grafana"
description: "Grafana analytics and monitoring platform"
url: "https://github.com/bborchers/ha-addons-grafana/tree/main/grafana"
arch:
  - aarch64
  - amd64
init: false
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Grafana Web UI"
options:
  log_level: info
  admin_user: "admin"
  admin_password: "admin"
  anonymous_access: false
  smtp_enabled: false
schema:
  log_level: list(debug|info|warn|error|critical)
  admin_user: str
  admin_password: password
  anonymous_access: bool
  root_url: str?
  domain: str?
  smtp_enabled: bool
  smtp_host: str?
  smtp_user: str?
  smtp_password: password?
  smtp_from_address: str?
  smtp_from_name: str?
  smtp_skip_verify: bool?
  smtp_starttls_policy: list(OpportunisticStartTLS|MandatoryStartTLS|NoStartTLS)?
